# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 思仟致远
email: 391506773@qq.com
description: > # this means to ignore newlines until "baseurl:"
  是不是傻？
  不好说...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ktfun.github.io/" # the base hostname & protocol for your site
twitter_username: ktfun
github_username:  ktfun

# Build settings
markdown: kramdown
